route:
  group_by: ['alertname']
  group_wait: 20s
  group_interval: 1m
  repeat_interval: 1h 
  receiver: discord_webhook

receivers:
- name: 'discord_webhook'
  webhook_configs:
  - url: 'http://discord-alertmanager:9094'