version: "3"
services:

  webapp:
    build: ./flask_app/.
    container_name: flask-app
    ports:
      - "5000:5000"
      - "8010:8010"
    volumes:
    - "./flask_app/app.py:/app.py"
    deploy:
      mode: global
  
  monitoring-prometheus:
    image: prom/prometheus:latest
    container_name: monitoring-prometheus
    ports:
    - "9090:9090"
    volumes:
    - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    - "./rules.yml:/etc/prometheus/rules.yml"
    deploy:
      mode: global
  
  example-grafana:
    image: grafana/grafana:latest
    container_name: monitoring-grafana
    depends_on:
      - monitoring-prometheus
    ports:
    - "3000:3000"
    volumes:
    - "./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml"
    - "./dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml"
    - "./project_dashboard.json:/etc/grafana/provisioning/dashboards/project_dashboard.json"
    env_file:
    - "./config.monitoring"
    deploy:
      mode: global
  
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - 9100:9100
    pid: host
    restart: always
    deploy:
      mode: global

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - 9093:9093
    volumes:
      - "./alertmanager.yml:/etc/alertmanager/alertmanager.yml"
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/alertmanager"
    deploy:
      mode: global
  
  discord-alermanager:
    image: benjojo/alertmanager-discord
    container_name: discord-alertmanager
    environment:
      - DISCORD_WEBHOOK=https://discord.com/api/webhooks/949932324030660628/Otqhi-BRsC7in_c9iWgsFoSJo1byai3bVJcbSTSBZww_BEuiUXAt2dOCuWqt8JbcmmLw
    restart: always