global:
 scrape_interval:       15s 
 evaluation_interval:   15s

rule_files:
  - rules.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
    - targets: ['monitoring-prometheus:9090']

  - job_name: 'flask-app'
    scrape_interval: 5s
    static_configs:
    - targets: ['flask-app:5000']

  - job_name: node
    static_configs:
    - targets: 
      - 'node-exporter:9100'